# Generated by Django 2.0.5 on 2019-01-09 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(blank=True, default=0, help_text='1->Active, 0->Inactive', null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
