# Generated by Django 2.0.5 on 2019-01-09 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 9, 16, 35, 22, 121736)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 16, 35, 22, 121648)),
        ),
    ]
